import { LevelDef, Obstacle } from '../types/game';

// Helper to create boundary walls for any map dimensions
function createBoundaryWalls(mapW: number, mapH: number, thickness = 24): Obstacle[] {
  return [
    // Top
    {
      id: 'boundary_top',
      type: 'wall',
      x: mapW / 2,
      y: thickness / 2,
      width: mapW,
      height: thickness,
      color: '#334155',
    },
    // Bottom
    {
      id: 'boundary_bottom',
      type: 'wall',
      x: mapW / 2,
      y: mapH - thickness / 2,
      width: mapW,
      height: thickness,
      color: '#334155',
    },
    // Left
    {
      id: 'boundary_left',
      type: 'wall',
      x: thickness / 2,
      y: mapH / 2,
      width: thickness,
      height: mapH,
      color: '#334155',
    },
    // Right
    {
      id: 'boundary_right',
      type: 'wall',
      x: mapW - thickness / 2,
      y: mapH / 2,
      width: thickness,
      height: mapH,
      color: '#334155',
    },
  ];
}

export const LEVELS: LevelDef[] = [
  // ================= LEVEL 1 =================
  {
    id: 1,
    title: 'LEVEL 1 — BEGINNER',
    subtitle: 'Drive straight and park in the open bay',
    timeLimit: 45,
    mapWidth: 1000,
    mapHeight: 700,
    theme: 'plaza',
    description: 'A spacious open plaza with plenty of maneuvering room. Perfect for getting familiar with vehicle steering and braking.',
    hint: 'Use W / Up Arrow to accelerate and SPACE or Down Arrow to stop inside the yellow lines.',
    carStart: {
      x: 180,
      y: 350,
      angle: Math.PI / 2, // facing right
    },
    parkingZone: {
      x: 780,
      y: 350,
      width: 64,
      height: 98,
      angle: Math.PI / 2, // horizontal slot facing right
      targetAngle: Math.PI / 2,
      label: 'PARK',
    },
    obstacles: [
      ...createBoundaryWalls(1000, 700),
      // Road guide curbs and gentle planters
      {
        id: 'l1_curb_top',
        type: 'curb',
        x: 500,
        y: 190,
        width: 600,
        height: 18,
        color: '#475569',
      },
      {
        id: 'l1_curb_bottom',
        type: 'curb',
        x: 500,
        y: 510,
        width: 600,
        height: 18,
        color: '#475569',
      },
      // Two gentle guidance cones
      {
        id: 'l1_cone_1',
        type: 'cone',
        x: 480,
        y: 240,
        width: 20,
        height: 20,
        radius: 10,
      },
      {
        id: 'l1_cone_2',
        type: 'cone',
        x: 480,
        y: 460,
        width: 20,
        height: 20,
        radius: 10,
      },
      // Decorative planters at edges
      {
        id: 'l1_planter_1',
        type: 'planter',
        x: 880,
        y: 200,
        width: 60,
        height: 36,
        color: '#166534',
      },
      {
        id: 'l1_planter_2',
        type: 'planter',
        x: 880,
        y: 500,
        width: 60,
        height: 36,
        color: '#166534',
      },
    ],
  },

  // ================= LEVEL 2 =================
  {
    id: 2,
    title: 'LEVEL 2 — EASY PARKING',
    subtitle: 'Navigate between parked cars into the open bay',
    timeLimit: 40,
    mapWidth: 1000,
    mapHeight: 700,
    theme: 'suburban',
    description: 'A commercial supermarket parking lot. Multiple parked vehicles line the bays; steer gently into your assigned stall.',
    hint: 'Take the gentle right turn and align your car straight between the parked vehicles.',
    carStart: {
      x: 180,
      y: 550,
      angle: 0, // facing up
    },
    parkingZone: {
      x: 720,
      y: 240,
      width: 56,
      height: 90,
      angle: 0, // vertical slot facing up
      targetAngle: 0,
      label: 'PARK',
    },
    obstacles: [
      ...createBoundaryWalls(1000, 700),
      // Left and center lane divider island
      {
        id: 'l2_island',
        type: 'curb',
        x: 380,
        y: 420,
        width: 24,
        height: 340,
        color: '#475569',
      },
      // Parked cars on the parking row
      {
        id: 'l2_car_1',
        type: 'car',
        x: 580,
        y: 240,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#2563EB', carType: 'sedan' },
      },
      {
        id: 'l2_car_2',
        type: 'car',
        x: 860,
        y: 240,
        width: 38,
        height: 70,
        angle: 0,
        details: { carColor: '#DC2626', carType: 'suv' },
      },
      // Additional parked cars on bottom row
      {
        id: 'l2_car_3',
        type: 'car',
        x: 580,
        y: 460,
        width: 36,
        height: 68,
        angle: Math.PI,
        details: { carColor: '#4B5563', carType: 'sedan' },
      },
      {
        id: 'l2_car_4',
        type: 'car',
        x: 720,
        y: 460,
        width: 36,
        height: 68,
        angle: Math.PI,
        details: { carColor: '#D97706', carType: 'coupe' },
      },
      // Guidance cones
      {
        id: 'l2_cone_1',
        type: 'cone',
        x: 380,
        y: 220,
        width: 18,
        height: 18,
        radius: 9,
      },
    ],
  },

  // ================= LEVEL 3 =================
  {
    id: 3,
    title: 'LEVEL 3 — 90 DEGREE TURN',
    subtitle: 'Make sharp 90-degree turns around traffic cones',
    timeLimit: 40,
    mapWidth: 1000,
    mapHeight: 700,
    theme: 'garage',
    description: 'Precision turning required. Thread through two consecutive perpendicular corners marked by cones to reach the parking stall.',
    hint: 'Slow down before turning! Full steering lock at low speed gives you tightest turning radius.',
    carStart: {
      x: 140,
      y: 180,
      angle: Math.PI / 2, // facing right
    },
    parkingZone: {
      x: 800,
      y: 530,
      width: 54,
      height: 86,
      angle: Math.PI / 2, // horizontal slot facing right
      targetAngle: Math.PI / 2,
      label: 'PARK',
    },
    obstacles: [
      ...createBoundaryWalls(1000, 700),
      // Central structural wall dividing the chicane
      {
        id: 'l3_wall_1',
        type: 'wall',
        x: 480,
        y: 280,
        width: 440,
        height: 28,
        color: '#64748B',
      },
      {
        id: 'l3_wall_2',
        type: 'wall',
        x: 260,
        y: 490,
        width: 320,
        height: 28,
        color: '#64748B',
      },
      // Traffic cones marking corners
      {
        id: 'l3_cone_1',
        type: 'cone',
        x: 680,
        y: 180,
        width: 18,
        height: 18,
        radius: 9,
      },
      {
        id: 'l3_cone_2',
        type: 'cone',
        x: 740,
        y: 260,
        width: 18,
        height: 18,
        radius: 9,
      },
      {
        id: 'l3_cone_3',
        type: 'cone',
        x: 240,
        y: 380,
        width: 18,
        height: 18,
        radius: 9,
      },
      {
        id: 'l3_cone_4',
        type: 'cone',
        x: 160,
        y: 420,
        width: 18,
        height: 18,
        radius: 9,
      },
      // Parked car near parking entrance
      {
        id: 'l3_car_1',
        type: 'car',
        x: 800,
        y: 410,
        width: 36,
        height: 68,
        angle: Math.PI / 2,
        details: { carColor: '#059669', carType: 'sedan' },
      },
    ],
  },

  // ================= LEVEL 4 =================
  {
    id: 4,
    title: 'LEVEL 4 — NARROW ROAD',
    subtitle: 'Maintain steady center alignment between strict walls',
    timeLimit: 35,
    mapWidth: 1050,
    mapHeight: 700,
    theme: 'industrial',
    description: 'A tight industrial alleyway with heavy concrete walls on both sides. Precision steering is required to avoid scratching your fenders.',
    hint: 'Small, gentle taps on steering keys (A/D or Left/Right) are better than holding them down.',
    carStart: {
      x: 120,
      y: 350,
      angle: Math.PI / 2, // facing right
    },
    parkingZone: {
      x: 930,
      y: 350,
      width: 52,
      height: 84,
      angle: Math.PI / 2,
      targetAngle: Math.PI / 2,
      label: 'PARK',
    },
    obstacles: [
      ...createBoundaryWalls(1050, 700),
      // Top corridor wall
      {
        id: 'l4_corridor_top',
        type: 'wall',
        x: 520,
        y: 265,
        width: 720,
        height: 32,
        color: '#475569',
      },
      // Bottom corridor wall
      {
        id: 'l4_corridor_bottom',
        type: 'wall',
        x: 520,
        y: 435,
        width: 720,
        height: 32,
        color: '#475569',
      },
      // Protruding obstacles in the corridor
      {
        id: 'l4_barrier_1',
        type: 'barrier',
        x: 360,
        y: 300,
        width: 24,
        height: 40,
        color: '#F59E0B',
      },
      {
        id: 'l4_barrier_2',
        type: 'barrier',
        x: 640,
        y: 400,
        width: 24,
        height: 40,
        color: '#F59E0B',
      },
      // Warning cones
      {
        id: 'l4_cone_1',
        type: 'cone',
        x: 360,
        y: 340,
        width: 18,
        height: 18,
        radius: 9,
      },
      {
        id: 'l4_cone_2',
        type: 'cone',
        x: 640,
        y: 360,
        width: 18,
        height: 18,
        radius: 9,
      },
      // Rear wall barrier behind the parking spot
      {
        id: 'l4_rear_wall',
        type: 'wall',
        x: 995,
        y: 350,
        width: 22,
        height: 120,
        color: '#64748B',
      },
    ],
  },

  // ================= LEVEL 5 =================
  {
    id: 5,
    title: 'LEVEL 5 — REVERSE PARKING',
    subtitle: 'Reverse backward into the designated bay',
    timeLimit: 35,
    mapWidth: 1000,
    mapHeight: 700,
    theme: 'night',
    description: 'Reverse parking test. Pull forward to position your car, then shift into reverse (S / Down Arrow) and back cleanly into the bay.',
    hint: 'Drive forward past the bay, then hold S/Down while turning into the slot in reverse.',
    carStart: {
      x: 300,
      y: 450,
      angle: Math.PI / 2, // facing right
    },
    parkingZone: {
      x: 320,
      y: 190,
      width: 50,
      height: 82,
      angle: 0, // vertical slot
      targetAngle: 0, // car should be facing up, which means backed into from below
      requireReverse: true,
      label: 'REVERSE',
    },
    obstacles: [
      ...createBoundaryWalls(1000, 700),
      // Left parked car beside the reverse slot
      {
        id: 'l5_car_left',
        type: 'car',
        x: 210,
        y: 190,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#6366F1', carType: 'sedan' },
      },
      // Right parked car beside the reverse slot
      {
        id: 'l5_car_right',
        type: 'car',
        x: 430,
        y: 190,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#9333EA', carType: 'suv' },
      },
      // Median wall preventing driving all the way forward
      {
        id: 'l5_divider',
        type: 'curb',
        x: 750,
        y: 450,
        width: 24,
        height: 260,
        color: '#475569',
      },
      // Barrier at the end of the aisle
      {
        id: 'l5_barrier',
        type: 'barrier',
        x: 900,
        y: 350,
        width: 26,
        height: 180,
        color: '#EAB308',
      },
      // Cones marking the curb
      {
        id: 'l5_cone_1',
        type: 'cone',
        x: 520,
        y: 320,
        width: 18,
        height: 18,
        radius: 9,
      },
      {
        id: 'l5_cone_2',
        type: 'cone',
        x: 640,
        y: 560,
        width: 18,
        height: 18,
        radius: 9,
      },
    ],
  },

  // ================= LEVEL 6 =================
  {
    id: 6,
    title: 'LEVEL 6 — TRAFFIC PARKING',
    subtitle: 'Weave through congested parked cars to the VIP spot',
    timeLimit: 35,
    mapWidth: 1050,
    mapHeight: 700,
    theme: 'suburban',
    description: 'A crowded parking lot during rush hour. Parked vehicles and shopping barriers leave very tight passageways.',
    hint: 'Keep a safe distance from car corners when turning.',
    carStart: {
      x: 120,
      y: 180,
      angle: Math.PI / 2, // facing right
    },
    parkingZone: {
      x: 900,
      y: 540,
      width: 48,
      height: 80,
      angle: 0,
      targetAngle: 0,
      label: 'PARK',
    },
    obstacles: [
      ...createBoundaryWalls(1050, 700),
      // Row 1 parked cars
      {
        id: 'l6_c1',
        type: 'car',
        x: 320,
        y: 180,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#EF4444', carType: 'sedan' },
      },
      {
        id: 'l6_c2',
        type: 'car',
        x: 420,
        y: 180,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#10B981', carType: 'coupe' },
      },
      {
        id: 'l6_c3',
        type: 'car',
        x: 520,
        y: 180,
        width: 38,
        height: 70,
        angle: 0,
        details: { carColor: '#3B82F6', carType: 'suv' },
      },
      // Row 2 parked cars (staggered in the middle)
      {
        id: 'l6_c4',
        type: 'car',
        x: 420,
        y: 380,
        width: 36,
        height: 68,
        angle: Math.PI / 2,
        details: { carColor: '#F59E0B', carType: 'sedan' },
      },
      {
        id: 'l6_c5',
        type: 'car',
        x: 600,
        y: 380,
        width: 36,
        height: 68,
        angle: Math.PI / 2,
        details: { carColor: '#6B7280', carType: 'coupe' },
      },
      // Target area cars on both sides of parkingZone
      {
        id: 'l6_c6',
        type: 'car',
        x: 790,
        y: 540,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#8B5CF6', carType: 'sedan' },
      },
      {
        id: 'l6_c7',
        type: 'car',
        x: 990,
        y: 540,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#EC4899', carType: 'coupe' },
      },
      // Barriers
      {
        id: 'l6_b1',
        type: 'barrier',
        x: 740,
        y: 220,
        width: 140,
        height: 22,
        color: '#EAB308',
      },
      // Cones
      {
        id: 'l6_cone_1',
        type: 'cone',
        x: 230,
        y: 320,
        width: 18,
        height: 18,
        radius: 9,
      },
      {
        id: 'l6_cone_2',
        type: 'cone',
        x: 700,
        y: 470,
        width: 18,
        height: 18,
        radius: 9,
      },
    ],
  },

  // ================= LEVEL 7 =================
  {
    id: 7,
    title: 'LEVEL 7 — S-CURVE',
    subtitle: 'Steer through a fluid S-shaped chicane without hitting cones',
    timeLimit: 30,
    mapWidth: 1050,
    mapHeight: 700,
    theme: 'rooftop',
    description: 'A rooftop parking deck with an S-curve track laid out with high-visibility cones and steel guardrails.',
    hint: 'Counter-steer smoothly as you transition between the first curve and second curve.',
    carStart: {
      x: 130,
      y: 540,
      angle: 0, // facing up
    },
    parkingZone: {
      x: 920,
      y: 180,
      width: 48,
      height: 78,
      angle: 0,
      targetAngle: 0,
      label: 'PARK',
    },
    obstacles: [
      ...createBoundaryWalls(1050, 700),
      // Left curve inner barrier
      {
        id: 'l7_wall_1',
        type: 'wall',
        x: 280,
        y: 320,
        width: 32,
        height: 340,
        color: '#64748B',
      },
      // Right curve inner barrier
      {
        id: 'l7_wall_2',
        type: 'wall',
        x: 580,
        y: 420,
        width: 32,
        height: 340,
        color: '#64748B',
      },
      // Cones shaping the top apex
      { id: 'l7_c_1', type: 'cone', x: 280, y: 120, width: 18, height: 18, radius: 9 },
      { id: 'l7_c_2', type: 'cone', x: 360, y: 150, width: 18, height: 18, radius: 9 },
      { id: 'l7_c_3', type: 'cone', x: 440, y: 210, width: 18, height: 18, radius: 9 },
      { id: 'l7_c_4', type: 'cone', x: 500, y: 280, width: 18, height: 18, radius: 9 },
      // Cones shaping the bottom apex
      { id: 'l7_c_5', type: 'cone', x: 650, y: 560, width: 18, height: 18, radius: 9 },
      { id: 'l7_c_6', type: 'cone', x: 740, y: 530, width: 18, height: 18, radius: 9 },
      { id: 'l7_c_7', type: 'cone', x: 810, y: 460, width: 18, height: 18, radius: 9 },
      // Parked car near destination
      {
        id: 'l7_parked_1',
        type: 'car',
        x: 820,
        y: 180,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#1E40AF', carType: 'sedan' },
      },
      // Planters
      {
        id: 'l7_pl_1',
        type: 'planter',
        x: 920,
        y: 330,
        width: 44,
        height: 44,
        color: '#15803D',
      },
    ],
  },

  // ================= LEVEL 8 =================
  {
    id: 8,
    title: 'LEVEL 8 — PRECISION PARKING',
    subtitle: 'Exact alignment into a tight parking stall',
    timeLimit: 30,
    mapWidth: 1000,
    mapHeight: 700,
    theme: 'garage',
    description: 'An underground parking garage with tight pillars and a compact bay. Alignment accuracy must be near perfect.',
    hint: 'Enter slowly. If you are angled inside the spot, back up slightly to straighten the wheels.',
    carStart: {
      x: 180,
      y: 520,
      angle: -Math.PI / 2, // facing left
    },
    parkingZone: {
      x: 520,
      y: 200,
      width: 46,
      height: 76,
      angle: 0,
      targetAngle: 0,
      label: 'PARK',
    },
    obstacles: [
      ...createBoundaryWalls(1000, 700),
      // Garage concrete pillars
      {
        id: 'l8_pillar_1',
        type: 'wall',
        x: 440,
        y: 200,
        width: 36,
        height: 76,
        color: '#475569',
      },
      {
        id: 'l8_pillar_2',
        type: 'wall',
        x: 600,
        y: 200,
        width: 36,
        height: 76,
        color: '#475569',
      },
      // Parked cars flanking the pillars
      {
        id: 'l8_car_1',
        type: 'car',
        x: 350,
        y: 200,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#B91C1C', carType: 'sedan' },
      },
      {
        id: 'l8_car_2',
        type: 'car',
        x: 690,
        y: 200,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#047857', carType: 'suv' },
      },
      // Central traffic islands
      {
        id: 'l8_island_1',
        type: 'curb',
        x: 340,
        y: 400,
        width: 240,
        height: 24,
        color: '#334155',
      },
      {
        id: 'l8_island_2',
        type: 'curb',
        x: 700,
        y: 400,
        width: 240,
        height: 24,
        color: '#334155',
      },
      // Cones
      { id: 'l8_cone_1', type: 'cone', x: 440, y: 290, width: 18, height: 18, radius: 9 },
      { id: 'l8_cone_2', type: 'cone', x: 600, y: 290, width: 18, height: 18, radius: 9 },
    ],
  },

  // ================= LEVEL 9 =================
  {
    id: 9,
    title: 'LEVEL 9 — EXPERT',
    subtitle: 'Fast-paced complex navigation with tight margin for error',
    timeLimit: 25,
    mapWidth: 1100,
    mapHeight: 700,
    theme: 'night',
    description: 'Expert-level course. A high-density obstacle labyrinth requiring confident acceleration and surgical braking.',
    hint: 'Commit to your steering inputs early. Keep momentum through corners.',
    carStart: {
      x: 120,
      y: 600,
      angle: 0, // facing up
    },
    parkingZone: {
      x: 960,
      y: 150,
      width: 44,
      height: 74,
      angle: 0,
      targetAngle: 0,
      label: 'PARK',
    },
    obstacles: [
      ...createBoundaryWalls(1100, 700),
      // Maze walls
      {
        id: 'l9_w1',
        type: 'wall',
        x: 260,
        y: 420,
        width: 28,
        height: 400,
        color: '#64748B',
      },
      {
        id: 'l9_w2',
        type: 'wall',
        x: 480,
        y: 260,
        width: 28,
        height: 420,
        color: '#64748B',
      },
      {
        id: 'l9_w3',
        type: 'wall',
        x: 720,
        y: 440,
        width: 28,
        height: 380,
        color: '#64748B',
      },
      // Parked cars
      {
        id: 'l9_car_1',
        type: 'car',
        x: 370,
        y: 560,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#D97706', carType: 'sedan' },
      },
      {
        id: 'l9_car_2',
        type: 'car',
        x: 600,
        y: 160,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#2563EB', carType: 'coupe' },
      },
      {
        id: 'l9_car_3',
        type: 'car',
        x: 850,
        y: 150,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#DC2626', carType: 'suv' },
      },
      // Cones
      { id: 'l9_c1', type: 'cone', x: 260, y: 160, width: 18, height: 18, radius: 9 },
      { id: 'l9_c2', type: 'cone', x: 480, y: 520, width: 18, height: 18, radius: 9 },
      { id: 'l9_c3', type: 'cone', x: 720, y: 200, width: 18, height: 18, radius: 9 },
      { id: 'l9_c4', type: 'cone', x: 880, y: 320, width: 18, height: 18, radius: 9 },
    ],
  },

  // ================= LEVEL 10 =================
  {
    id: 10,
    title: 'LEVEL 10 — PARKING MASTER',
    subtitle: 'The Ultimate Parking Test: 20 seconds, zero mistakes',
    timeLimit: 20,
    mapWidth: 1100,
    mapHeight: 700,
    theme: 'rooftop',
    description: 'The master challenge. Intricate obstacles, luxury vehicles on both flanks, tight turns, and a strict 20-second countdown clock.',
    hint: 'Every millisecond counts! Accelerate cleanly, make sharp controlled turns, and slam the brakes right inside the yellow box.',
    carStart: {
      x: 130,
      y: 350,
      angle: Math.PI / 2, // facing right
    },
    parkingZone: {
      x: 960,
      y: 350,
      width: 43,
      height: 73,
      angle: Math.PI / 2, // horizontal slot
      targetAngle: Math.PI / 2,
      label: 'MASTER',
    },
    obstacles: [
      ...createBoundaryWalls(1100, 700),
      // Central maze blocks
      {
        id: 'l10_b1',
        type: 'barrier',
        x: 320,
        y: 250,
        width: 140,
        height: 24,
        color: '#EAB308',
      },
      {
        id: 'l10_b2',
        type: 'barrier',
        x: 320,
        y: 450,
        width: 140,
        height: 24,
        color: '#EAB308',
      },
      {
        id: 'l10_island',
        type: 'wall',
        x: 540,
        y: 350,
        width: 44,
        height: 200,
        color: '#64748B',
      },
      // Multiple parked luxury cars
      {
        id: 'l10_car_top1',
        type: 'car',
        x: 740,
        y: 190,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#9333EA', carType: 'coupe' },
      },
      {
        id: 'l10_car_top2',
        type: 'car',
        x: 850,
        y: 190,
        width: 36,
        height: 68,
        angle: 0,
        details: { carColor: '#DC2626', carType: 'sedan' },
      },
      {
        id: 'l10_car_bot1',
        type: 'car',
        x: 740,
        y: 510,
        width: 36,
        height: 68,
        angle: Math.PI,
        details: { carColor: '#2563EB', carType: 'sedan' },
      },
      {
        id: 'l10_car_bot2',
        type: 'car',
        x: 850,
        y: 510,
        width: 38,
        height: 70,
        angle: Math.PI,
        details: { carColor: '#059669', carType: 'suv' },
      },
      // Flanking cars right next to the master parking spot!
      {
        id: 'l10_car_flank_top',
        type: 'car',
        x: 960,
        y: 260,
        width: 36,
        height: 68,
        angle: Math.PI / 2,
        details: { carColor: '#E11D48', carType: 'coupe' },
      },
      {
        id: 'l10_car_flank_bot',
        type: 'car',
        x: 960,
        y: 440,
        width: 36,
        height: 68,
        angle: Math.PI / 2,
        details: { carColor: '#475569', carType: 'sedan' },
      },
      // Cones
      { id: 'l10_cone_1', type: 'cone', x: 220, y: 350, width: 18, height: 18, radius: 9 },
      { id: 'l10_cone_2', type: 'cone', x: 440, y: 220, width: 18, height: 18, radius: 9 },
      { id: 'l10_cone_3', type: 'cone', x: 440, y: 480, width: 18, height: 18, radius: 9 },
      { id: 'l10_cone_4', type: 'cone', x: 640, y: 350, width: 18, height: 18, radius: 9 },
    ],
  },
];
